accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login"
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignUp.as_view(), name="signup"),
]

posts/urls.py
from django.urls import path

from posts import views

app_name = "posts"

urlpatterns = [
    path("", views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/", views.UserPost.as_view(), name="for_user"),
    path("by/<username>/<int:pk>/", views.PostDetail.as_view(), name="single"),
    path("delete/<int:pk>/", views.DeletePost.as_view(), name="delete")
]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from simplesocial import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.HomePage.as_view(), name="home"),

    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),

    path("test/", views.TestPage.as_view(), name="test"),
    path("thanks/", views.ThanksPage.as_view(), name="thanks"),

    path("posts/", include(("posts.urls", "posts"), namespace="posts")),
    path("groups/", include(("groups.urls", "groups"), namespace="groups")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls))
    ] + urlpatterns

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU"
        crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css' %}">

    <title>Document</title>
</head>

<body>
    
    <nav class="mynavb navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'home' %}">Star Social</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'posts:create' %}">Post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'groups:all' %}">Group</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'groups:create' %}">Create Group</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'groups:all' %}">Groups</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container mycontent">
        {% block content %}
        {% endblock %}
    </div>
    <canvas id="canvas"></canvas>
    <span id="note">Click to add fireflies</span>
</body>
<script type="text/javascript" src="{% static 'simplesocial/js/master.js' %}"></script>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script>

</html>

templates/index.html
{% extends "base.html" %}

{% block content %}

<h1>Wellcome to index page</h1>

{% endblock %}

templates/test.html
{% extends "base.html" %}

{% block content %}

<h1>You are loged in</h1>
<h1>test</h1>

{% endblock %}

templates/thanks.html
{% extends "base.html" %}

{% block content %}

<h1>You are logout</h1>
<h1>Thnaks</h1>

{% endblock %}